<div class="nav">
	<ul>
		<li><a <?php if ($thisPage=="Index") echo " class=\"is-current\""; ?> href="index.php">Home</a></li>
		<li><a <?php if ($thisPage=="Ostriker") echo " class=\"is-current\""; ?> href="ostriker.php">Oliver Ostriker</a></li>
		<li><a <?php if ($thisPage=="Aziz") echo " class=\"is-current\""; ?> href="aziz.php">Zubair Aziz</a></li>
		<li><a <?php if ($thisPage=="Agusi") echo " class=\"is-current\""; ?> href="agusi.php">Kennedy Agusi</a></li>
	</ul>
</div>
