<h1>Beijing -- Assignment 03</h1>
<p class="subtitle">Professional Portfolio</p>

<div class="nav">
	<ul>
		<li><a href="urcsc174.org/assignment03/beijing/index.php">Home</a></li>
		<li><a href="urcsc174.org/assignment03/beijing/ostriker.php">Oliver Ostriker</a></li>
		<li><a href="urcsc174.org/assignment03/beijing/aziz.php">Zubair Aziz</a></li>
		<li><a href="urcsc174.org/assignment03/beijing/agusi.php">Kennedy Agusi</a></li>
	</ul>
</div>
